operations:
  get:
    operationId: getProductById
    tags:
      - products
    summary: Get product by ID
    description: |
      指定された商品IDに基づいて、単一の商品情報を取得します。
      このエンドポイントは、商品の詳細表示や編集のために利用されます。
    parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetProductByIdResponse'
components:
  schemas:
    GetProductByIdResponse:
      $ref: ../../components/schemas/products/Product.yaml#/Product
